### ISSUE TITLE
bug when you change date task that already has

### ISSUE THREAD

**Issue by Klastes** [dmfs/tasks#125]
When changing date task that has end date ,  touching this date in calendar view causes immedietly crash. This happen on note 4 n910c 5.0.1.
Could you add the button in quick view of task (there are +1 hr and +1m) that set the current date as end date?

**Comment by dmfs** [comment]
Did you send a crash report via Google Play or do you have a log of the crash?

Do you want the "due today" button only for tasks that have no due date yet?

**Comment by Klastes** [comment]
Hello.
Today I've send the repport to google - problem still exist.
I think the best option is the button visible for all task (for empty ones and with due date).
Dnia 8 marca 2015 23:40 Marten Gajda napisał(a):
 Did you send a crash report via Google Play or do you have a log of the crash?Do you want the "due today" button only for tasks that have no due date yet?—

**Comment by dmfs** [comment]
Thanks, I got it. Looks like a bug in Samsung's Android. There already is a report on StackOverflow about this issue:
http://stackoverflow.com/questions/28345413/datepicker-crash-in-samsung-with-android-5-0

We'll look for a workaround.

**Comment by dmfs** [comment]
is your language set to French?
Someone reported it happens only when the language is set to French: http://stackoverflow.com/questions/28618405/datepicker-crashes-on-my-device-when-clicked-with-personal-app

**Comment by Klastes** [comment]
My language is polish.


Wysłano z mojego urządzenia Samsung

-------- Oryginalna wiadomość --------
Od: Marten Gajda <notifications@github.com> 
Data: 11.03.2015  12:07  (GMT+01:00) 
Do: dmfs/tasks <tasks@noreply.github.com> 
DW: Klastes <klastes@tlen.pl> 
Temat: Re: [tasks] bug when you change date task that already has (#125) 

is your language set to French?

Someone reported it happens only when the language is set to French: http://stackoverflow.com/questions/28618405/datepicker-crashes-on-my-device-when-clicked-with-personal-app

**Comment by Klastes** [comment]
And if You could add also tommorow button. It would be a very big improvment for your  already great aplication.

Wysłano z mojego urządzenia Samsung

-------- Oryginalna wiadomość --------
Od: Marten Gajda <notifications@github.com> 
Data: 11.03.2015  12:07  (GMT+01:00) 
Do: dmfs/tasks <tasks@noreply.github.com> 
DW: Klastes <klastes@tlen.pl> 
Temat: Re: [tasks] bug when you change date task that already has (#125) 

is your language set to French?

Someone reported it happens only when the language is set to French: http://stackoverflow.com/questions/28618405/datepicker-crashes-on-my-device-when-clicked-with-personal-app

**Comment by dmfs** [comment]
Can you check if it crashes when you set the device language to English?

We'll see what we can do with the date selection. In general we want to avoid too many UI elements in the details view. So adding more buttons would be counter productive. But if we think it's useful we certainly can do that. We'll give it a try.

**Comment by Klastes** [comment]
You are right - when I switch to english problem dissappear and come back with returning to polish. I am hopefull that you add this features.
Wysłano z mojego urządzenia Samsung

-------- Oryginalna wiadomość --------
Od: Marten Gajda <notifications@github.com> 
Data: 11.03.2015  14:35  (GMT+01:00) 
Do: dmfs/tasks <tasks@noreply.github.com> 
DW: Klastes <klastes@tlen.pl> 
Temat: Re: [tasks] bug when you change date task that already has (#125) 

Can you check if it crashes when you set the device language to English?

We'll see what we can do with the date selection. In general we want to avoid too many UI elements in the details view. So adding more buttons would be counter productive. But if we think it's useful we certainly can do that. We'll give it a try.

**Comment by dmfs** [comment]
We'll add a workaround to fix this until Samsung releases a fix.
We're still thinking about the "today" buttons.

**Comment by dmfs** [comment]
This should be fixed in the latest release. We've added a fallback to use the old style date picker until Samsung has fixed the new date picker.

**Comment by dmfs** [comment]
Added #132 to remove keep track of the task to remove the workaround.
