### ISSUE TITLE
Use default title if empty

### ISSUE THREAD

**Issue by maulwuff** [dmfs/tasks#127]
I found myself several times where I had to take quick notes and left the title empty... bad mistake. On trying to save the notes/task, the app just says "empty title... not saving" (or similar) and the task has gone. 
Please use a default title instead if the task is not empty!

**Comment by dmfs** [comment]
I think we can just use the first line of the task description if there is any. I don't like the idea of using something like "(no title)" as title if none has been entered.

**Comment by dmfs** [comment]
fixed. The app now uses the first line of the description or the first check list item if no title has been entered. If both fails, the editor will still close without saving.
