### ISSUE TITLE
Widget (still) shows tasks with future start date

### ISSUE THREAD

**Issue by lkettenb** [dmfs/tasks#129]
I am sorry, but since you fixed #29 and I updated to the latest release all future events are shown in the widget again. Actually this bug was fixed for me months ago...

I am using CaldDAV-Sync 0.4.22 (AndroitPIT) and Tasks 1.1.5 with my personal OwnCloud.

**Comment by lkettenb** [comment]
I was able to solve the problem by choosing different start and end dates. If both are identical future tasks are shown in the widget. Is it a bug or a feature?

**Comment by dmfs** [comment]
Ah yes, that's actually a feature. We implemented it that way to support tasks created on Apple clients. Apple clients always set the start date to the due date.
