### ISSUE TITLE
Feature Request: notifications on startup

### ISSUE THREAD

**Issue by mikeberger** [dmfs/tasks#131]
Can there be a option to show notifications for all overdue tasks on phone startup? Most of my tasks are all-day, so the task times are set to midnight. If my phone is off at midnight, I never get the notifications. Also, if a task is a few days overdue, I still would like to keep getting the notification each time the phone boots up.

**Comment by dmfs** [comment]
Will be fixed in the next release. You can pin notifications now, so they persist even over a reboot, see #86
