### ISSUE TITLE
Task list name not updated in mobile app

### ISSUE THREAD

**Issue by kbbl1977** [dmfs/tasks#145]
Hello,
just discovered a small bug in mobile task app.

After renaming a task list in owncloud (via web interface), name has not changed in mobile app.
Tried to refresh, but no luck.
Even after few weeks, tha name is stis old in mobile app.
And there is no way to change/update it in mobile app.

I'm using a tasklist plugin for thunderbird (with Lightning) and task list name in it has changed just fine.
Also on phne a'im using a calendar app, and calendar name is correct in there.
The calendar app is using same owncloud via caldav, just like the Tasks app.

Let me know if You'll need some more info.

Thanks for help
Tomas Novosad

**Comment by dmfs** [comment]
Thanks for the report. That's probably a bug in CalDAV-Sync. We'll check that.

**Comment by dmfs** [comment]
Closing this, since it's not an issue of this app.
