### ISSUE TITLE
Unauthorised 403 error when syncing with iCloud

### ISSUE THREAD

**Issue by danthe93** [dmfs/tasks#146]
Hi,

I am getting a 403 unauthorised error when trying to sync tasks with iCloud using Davdroid.

This only happens when setting a specific time for events, when editing or creating new tasks on my Android device. 

However, the tasks are synced fine when changing all other attributes, and sync fine when enabling "All Day" option.

Thanks.

**Comment by dmfs** [comment]
This is not an issue of this app. Please report to Davdroid instead.
