### ISSUE TITLE
Automatic syncing/refreshing

### ISSUE THREAD

**Issue by jluttine** [dmfs/tasks#147]
If I have understood correctly, the user needs to manually choose "Refresh" in the application in order to sync. Would it be possible to allow automatic syncing by providing a time interval (5min, 15min, 1hour, 1day, etc) of the sync operations?

**Comment by dmfs** [comment]
That's an issue of your sync app. At least in CalDAV-Sync there is an option to set an automatic sync interval.

**Comment by jluttine** [comment]
Ok, thanks!
