### ISSUE TITLE
Fruux app support

### ISSUE THREAD

**Issue by thenktor** [dmfs/tasks#150]
Hi,

please add Fruux app support to Tasks, so that it also shows tasks that are synchronized by the Fruux app.

Thanks

**Comment by dmfs** [comment]
It should work the other way round. The Fruux app would have to support this app, which is perfectly possible to implement. I'll talk to the Fruux guys.
I'm closing this issue, because we can't fix it in this app.

**Comment by thenktor** [comment]
OK, thanks. Isn't the Fruux app made by you, too?

**Comment by dmfs** [comment]
It is, but I still need to talk to Fruux first.

**Comment by thenktor** [comment]
Yes, of course ;)

**Comment by yoavram** [comment]
+1
where can we let know fruux we want this? the current fruux tasks app isn't up to tasks apps that sync with google...
