### ISSUE TITLE
Description not synced

### ISSUE THREAD

**Issue by jluttine** [dmfs/tasks#156]
It seems that description field of tasks isn't synced. Is this a lacking feature, a bug or something wrong with my clients/server? I'm using owncloud as the sync server.

**Comment by wweich** [comment]
I am also using Owncloud and CalDAV-Sync and the description of tasks is synced without problems.
It is definitely a bug.

**Comment by dmfs** [comment]
@jluttine which sync app do you use? CalDAV-Sync should sync descriptions correctly. Anyway, this is an issue of the sync app not of the task app, hence I'm closing this.
