### ISSUE TITLE
How to add new Task list?

### ISSUE THREAD

**Issue by keepkeeprunning** [dmfs/tasks#157]
There is no button. Users at play.store complain too.

**Comment by jalcine** [comment]
Tasks lists are controlled by your CalDev instance, no?

**Comment by jkufner** [comment]
You need to create a new calendar on your CalDAV server. This how CalDAV
works and it is out of Tasks' scope.

It should be possible to do this from CalDAV connector (the account sync
app), but I don't think it is implemented in any of them.
