### ISSUE TITLE
Enhancement request: omit list selection screen for single list or autoexpand

### ISSUE THREAD

**Issue by m-reiter** [dmfs/tasks#20]
I only use one single list of tasks, therefore the list selection screen is useless to me. Solutions for this case would be to autoexpand the only list on the existing screen or to just show all tasks without displaying the list name at all.

**Comment by dmfs** [comment]
I'm closing this. The app now persists the expansion status of the open groups, so this should be obsolete. For now we won't hide the list header if there is only one list, but we're currently thinking about a different UI concept that might work this way.
