### ISSUE TITLE
Desktop widget won't update on task change

### ISSUE THREAD

**Issue by ivask** [dmfs/tasks#41]
When i change task details or add new task in app, info on desktop widget won't update. In same time task list and tasks details in app is ok. This issues retry not often, but helps either removal and adding widget on desktop or restart phone.
I use tasks for caldav and ownclowd server on sony xperia zl with android 4.2.2. Info on server after sync in caldav is ok to. Click on buton update in app don't help.

**Comment by dmfs** [comment]
Is this still an issue with the latest release?

The `ContentResolver` error is not a problem. We know where it comes from and it shouldn't do any harm. Actually we see the same messages for the CalendarProvider.

**Comment by untitaker** [comment]
I think you can close this again... turned out I've been on a very old version, just updated. I'll bug you again if this is still an issue :)

**Comment by dmfs** [comment]
Ok, but I think it should work now :)
