### ISSUE TITLE
Keyboard input broken for checkbox items

### ISSUE THREAD

**Issue by maulwuff** [dmfs/tasks#84]
When adding new checkbox items,  there is a interruption in the input process after the first letter. 
On keyboards with word prediction this is canceled after the first letter. Swiping does work though -  if you get it right with the first try,  as any other word prediction is canceled immediately. (tested on an xperia active) 
On a galaxy Nexus with SwiftKey  it's easy to reproduce, too: switch to number keyboard and try typing 123. Right after the 1 the keyboard switches back to letter mode, you have to switch back to number mode to type 23.

**Comment by dmfs** [comment]
This issue should be fixed with 1.1. Please open a new bug if this is still an issue.
