### ISSUE TITLE
Feature request: Pin task as notification

### ISSUE THREAD

**Issue by jkufner** [dmfs/tasks#86]
**1st use case:** Shopping list.

I'm going to visit a grocery store, so I write down a task with many checkboxes (awsome feature!). But when I switch to other app this task gets lost somewhere in the list of many other tasks.

I would like to have checkbox to "pin" the task as notification, just like when its alarm goes off, but with slightly different icon (but that is not important).

This way I could keep the shopping list task easily available during my visit in the store.

**2nd use case:** To keep track of what I'm doing right now. Let's say I need to buy a tickets after visiting the grocery store (from previous use case) and then do some other things on different places. Traveling will take some time and it is easy to forget something. So before I go I would pin all the tasks for that particular trip to keep them in sight. I did that few times already with non-permanent calendar notifications and it is very handy.

You may ask why not to use 'Today' view for this. Well, pinned notifications allow you to select only relevant tasks for now and do not mix them with other things you need to do today, for example when you get back to office after the running around the town.

Thank you! :)

**Comment by dmfs** [comment]
We've implemented this in 1.1.7. At present there is no option in a notification itself to pin a task, but it's just one click away when you open the task. We decided to omit such an option, because we don't have much space in the notifications. If we come up with a better idea we'll add that option.
