### ISSUE TITLE
Move destructive actions to menu

### ISSUE THREAD

**Issue by jkufner** [dmfs/tasks#87]
Please move destructive actions away from toolbar. For example cancel button is just next to save button and it does not even ask if you really want to throw away your changes. The same with delete buton just next to edit button (this one at least asks).

This will also make a good place to put checkbox mentioned in #86 and some future features.

Thank you! :)

**Comment by dmfs** [comment]
We implemented this feature request partially. In the editor "cancel" and "save" are clearly separated now. The details view may still show "edit" and "delete" next to each other. I don't like the idea of adding a menu with just one item ("delete") if we don't have to. We'll implement a better solution if we can come up with one.
So I'll close this issue for now.
