### ISSUE TITLE
Feature request: Intent-Filter for Google Now

### ISSUE THREAD

**Issue by j3ernhard** [dmfs/tasks#92]
Add a Intent-Filter to create tasks via Google Now commands. 
Command in German: "Ok, Google"  "Notiz 'Das ist ein guter Vorschlag' "

I think you could use as title: "Sprachnotiz vom 2.8.2014" and as description the text content e.g. "Das ist ein guter Vorschlag".
Users could set a default calender for Google Now notes. 

Code: 
```
<intent-filter>
                <action android:name="com.google.android.gm.action.AUTO_SEND"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <data android:mimeType="*/*"/>
</intent-filter>
```

**Comment by dmfs** [comment]
@j3ernhard This should be present in the latest release. Have you tried it yet?

**Comment by dmfs** [comment]
closing this. It should work now.

**Comment by j3ernhard** [comment]
yes, it works :-) 
perfect.
